import type { Product, Review, Order, User } from '@/types';

export const categories = [
  'All',
  'Men',
  'Women',
  'Accessories',
  'Footwear',
  'Outerwear',
  'Activewear',
];

export const subcategories: Record<string, string[]> = {
  Men: ['Shirts', 'Pants', 'Suits', 'Casual'],
  Women: ['Dresses', 'Tops', 'Skirts', 'Pants'],
  Accessories: ['Bags', 'Watches', 'Jewelry', 'Belts'],
  Footwear: ['Sneakers', 'Boots', 'Heels', 'Sandals'],
  Outerwear: ['Jackets', 'Coats', 'Blazers'],
  Activewear: ['Gym', 'Yoga', 'Running'],
};

export const sizes = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];

export const colors = [
  { name: 'Black', hex: '#000000' },
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Navy', hex: '#1a237e' },
  { name: 'Gray', hex: '#757575' },
  { name: 'Beige', hex: '#d7ccc8' },
  { name: 'Red', hex: '#c62828' },
  { name: 'Green', hex: '#2e7d32' },
  { name: 'Blue', hex: '#1565c0' },
];

const unsplashImages = {
  men: [
    'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1598032895397-b9472444bf93?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&h=800&fit=crop',
  ],
  women: [
    'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1550614000-4b9519e02a48?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&h=800&fit=crop',
  ],
  accessories: [
    'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=800&fit=crop',
  ],
  footwear: [
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&h=800&fit=crop',
  ],
  outerwear: [
    'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&h=800&fit=crop',
  ],
  activewear: [
    'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=800&fit=crop',
    'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=800&fit=crop',
  ],
};

export const products: Product[] = [
  {
    _id: 'p1',
    name: 'Premium Wool Overcoat',
    description: 'Crafted from Italian merino wool, this overcoat features a tailored silhouette with notch lapels, welt pockets, and a full satin lining. Perfect for formal occasions or elevating everyday looks.',
    price: 489,
    originalPrice: 650,
    images: [unsplashImages.outerwear[0], unsplashImages.outerwear[1]],
    category: 'Outerwear',
    subcategory: 'Coats',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [colors[0], colors[2], colors[3]],
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    tags: ['winter', 'formal', 'classic'],
    brand: 'NOVA Atelier',
    createdAt: '2024-01-15',
  },
  {
    _id: 'p2',
    name: 'Silk Evening Dress',
    description: 'An elegant floor-length silk dress with a draped neckline and flowing skirt. The delicate fabric catches light beautifully, making it perfect for galas, weddings, and special evenings.',
    price: 329,
    originalPrice: 450,
    images: [unsplashImages.women[0], unsplashImages.women[1]],
    category: 'Women',
    subcategory: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [colors[1], colors[5], colors[0]],
    rating: 4.9,
    reviewCount: 89,
    inStock: true,
    tags: ['evening', 'elegant', 'silk'],
    brand: 'NOVA Atelier',
    createdAt: '2024-02-10',
  },
  {
    _id: 'p3',
    name: 'Minimalist Leather Sneakers',
    description: 'Handcrafted from full-grain Italian leather with a cushioned memory foam insole. The clean, minimalist design pairs effortlessly with everything from suits to jeans.',
    price: 189,
    originalPrice: 250,
    images: [unsplashImages.footwear[0], unsplashImages.footwear[1]],
    category: 'Footwear',
    subcategory: 'Sneakers',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: [colors[1], colors[0], colors[3]],
    rating: 4.7,
    reviewCount: 256,
    inStock: true,
    tags: ['casual', 'minimal', 'leather'],
    brand: 'NOVA Step',
    createdAt: '2024-01-20',
  },
  {
    _id: 'p4',
    name: 'Tailored Slim Fit Suit',
    description: 'A modern two-piece suit in premium stretch wool. Features a single-breasted jacket with peak lapels and flat-front trousers. The perfect foundation for a sharp, contemporary wardrobe.',
    price: 599,
    images: [unsplashImages.men[0], unsplashImages.men[1]],
    category: 'Men',
    subcategory: 'Suits',
    sizes: ['36', '38', '40', '42', '44'],
    colors: [colors[0], colors[2]],
    rating: 4.6,
    reviewCount: 78,
    inStock: true,
    tags: ['formal', 'business', 'tailored'],
    brand: 'NOVA Atelier',
    createdAt: '2024-03-05',
  },
  {
    _id: 'p5',
    name: 'Crossbody Leather Bag',
    description: 'Compact yet functional, this crossbody bag is made from vegetable-tanned leather with brushed gold hardware. Features multiple compartments for organized everyday carry.',
    price: 149,
    originalPrice: 199,
    images: [unsplashImages.accessories[0], unsplashImages.accessories[1]],
    category: 'Accessories',
    subcategory: 'Bags',
    sizes: ['One Size'],
    colors: [colors[0], colors[4], colors[3]],
    rating: 4.5,
    reviewCount: 167,
    inStock: true,
    tags: ['daily', 'leather', 'minimal'],
    brand: 'NOVA Carry',
    createdAt: '2024-02-28',
  },
  {
    _id: 'p6',
    name: 'Performance Training Set',
    description: 'Engineered with moisture-wicking fabric and 4-way stretch technology. This matching set includes a compression top and tapered joggers for peak gym performance.',
    price: 119,
    images: [unsplashImages.activewear[0], unsplashImages.activewear[1]],
    category: 'Activewear',
    subcategory: 'Gym',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [colors[0], colors[7], colors[6]],
    rating: 4.8,
    reviewCount: 312,
    inStock: true,
    tags: ['gym', 'performance', 'stretch'],
    brand: 'NOVA Sport',
    createdAt: '2024-01-08',
  },
  {
    _id: 'p7',
    name: 'Cashmere Turtleneck',
    description: 'Luxuriously soft Mongolian cashmere in a classic turtleneck silhouette. Lightweight yet warm, it layers beautifully under jackets or wears elegantly on its own.',
    price: 249,
    originalPrice: 320,
    images: [unsplashImages.men[2], unsplashImages.men[3]],
    category: 'Men',
    subcategory: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [colors[0], colors[4], colors[3]],
    rating: 4.9,
    reviewCount: 145,
    inStock: true,
    tags: ['luxury', 'cashmere', 'winter'],
    brand: 'NOVA Atelier',
    createdAt: '2024-03-12',
  },
  {
    _id: 'p8',
    name: 'Pleated Midi Skirt',
    description: 'A flowing pleated midi skirt with an elasticated waistband for all-day comfort. The lightweight fabric creates beautiful movement with every step.',
    price: 89,
    images: [unsplashImages.women[2], unsplashImages.women[3]],
    category: 'Women',
    subcategory: 'Skirts',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [colors[1], colors[5], colors[7]],
    rating: 4.4,
    reviewCount: 98,
    inStock: true,
    tags: ['casual', 'flowy', 'summer'],
    brand: 'NOVA Atelier',
    createdAt: '2024-02-15',
  },
  {
    _id: 'p9',
    name: 'Chronograph Watch',
    description: 'Swiss-made chronograph with sapphire crystal, stainless steel case, and genuine leather strap. Water-resistant to 100m with luminous hands for visibility in any condition.',
    price: 349,
    originalPrice: 499,
    images: [unsplashImages.accessories[2], unsplashImages.accessories[3]],
    category: 'Accessories',
    subcategory: 'Watches',
    sizes: ['One Size'],
    colors: [colors[0], colors[2]],
    rating: 4.7,
    reviewCount: 203,
    inStock: true,
    tags: ['luxury', 'swiss', 'classic'],
    brand: 'NOVA Time',
    createdAt: '2024-01-25',
  },
  {
    _id: 'p10',
    name: 'Chelsea Leather Boots',
    description: 'Hand-finished Chelsea boots in premium calfskin leather with elastic side panels and a durable rubber sole. The timeless design works with both casual and formal outfits.',
    price: 219,
    images: [unsplashImages.footwear[2], unsplashImages.footwear[3]],
    category: 'Footwear',
    subcategory: 'Boots',
    sizes: ['7', '8', '9', '10', '11'],
    colors: [colors[0], colors[4]],
    rating: 4.6,
    reviewCount: 134,
    inStock: true,
    tags: ['classic', 'leather', 'versatile'],
    brand: 'NOVA Step',
    createdAt: '2024-03-01',
  },
  {
    _id: 'p11',
    name: 'Bomber Jacket',
    description: 'A contemporary take on the classic bomber, featuring water-resistant nylon shell, ribbed trims, and a quilted lining. The relaxed fit allows for easy layering.',
    price: 159,
    originalPrice: 210,
    images: [unsplashImages.outerwear[2], unsplashImages.outerwear[3]],
    category: 'Outerwear',
    subcategory: 'Jackets',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [colors[0], colors[6], colors[5]],
    rating: 4.5,
    reviewCount: 187,
    inStock: true,
    tags: ['streetwear', 'casual', 'layering'],
    brand: 'NOVA Street',
    createdAt: '2024-02-20',
  },
  {
    _id: 'p12',
    name: 'Yoga Flow Set',
    description: 'Seamless yoga set with high-waist leggings and a supportive sports bra. The buttery-soft fabric provides compression without restriction for the perfect flow.',
    price: 79,
    images: [unsplashImages.activewear[2], unsplashImages.activewear[3]],
    category: 'Activewear',
    subcategory: 'Yoga',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [colors[4], colors[7], colors[1]],
    rating: 4.8,
    reviewCount: 278,
    inStock: true,
    tags: ['yoga', 'comfort', 'seamless'],
    brand: 'NOVA Sport',
    createdAt: '2024-03-08',
  },
  {
    _id: 'p13',
    name: 'Linen Blend Shirt',
    description: 'A breathable linen-cotton blend shirt with a relaxed fit and mother-of-pearl buttons. Perfect for warm-weather occasions with its natural texture and effortless drape.',
    price: 79,
    originalPrice: 110,
    images: [unsplashImages.men[4], unsplashImages.men[5]],
    category: 'Men',
    subcategory: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [colors[1], colors[4], colors[7]],
    rating: 4.3,
    reviewCount: 112,
    inStock: true,
    tags: ['summer', 'breathable', 'casual'],
    brand: 'NOVA Atelier',
    createdAt: '2024-03-15',
  },
  {
    _id: 'p14',
    name: 'Statement Blazer',
    description: 'A structured blazer with padded shoulders and a single-button closure. The tailored cut creates a powerful silhouette for the modern professional.',
    price: 279,
    images: [unsplashImages.women[4], unsplashImages.women[5]],
    category: 'Women',
    subcategory: 'Tops',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [colors[0], colors[2], colors[4]],
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    tags: ['professional', 'structured', 'power'],
    brand: 'NOVA Atelier',
    createdAt: '2024-02-05',
  },
  {
    _id: 'p15',
    name: 'Gold Chain Necklace',
    description: '14k gold-plated chain necklace with a paperclip link design. Layer it with other pieces or wear solo for a refined minimalist statement.',
    price: 69,
    originalPrice: 95,
    images: [unsplashImages.accessories[1], unsplashImages.accessories[2]],
    category: 'Accessories',
    subcategory: 'Jewelry',
    sizes: ['One Size'],
    colors: [colors[4]],
    rating: 4.4,
    reviewCount: 89,
    inStock: true,
    tags: ['minimal', 'gold', 'layering'],
    brand: 'NOVA Luxe',
    createdAt: '2024-03-20',
  },
  {
    _id: 'p16',
    name: 'Running Performance Shoes',
    description: 'Ultra-lightweight running shoes with responsive foam cushioning and breathable knit upper. The carbon-fiber plate provides explosive energy return with every stride.',
    price: 179,
    images: [unsplashImages.footwear[1], unsplashImages.footwear[0]],
    category: 'Footwear',
    subcategory: 'Sneakers',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: [colors[6], colors[7], colors[0]],
    rating: 4.9,
    reviewCount: 445,
    inStock: true,
    tags: ['running', 'performance', 'lightweight'],
    brand: 'NOVA Sport',
    createdAt: '2024-01-30',
  },
];

export const reviews: Review[] = [
  {
    _id: 'r1',
    productId: 'p1',
    userId: 'u1',
    userName: 'Alexandra M.',
    rating: 5,
    title: 'Exceptional quality',
    comment: 'The wool is incredibly soft and the tailoring is impeccable. This coat elevates every outfit I pair it with. Worth every penny.',
    helpful: 24,
    createdAt: '2024-03-10',
  },
  {
    _id: 'r2',
    productId: 'p1',
    userId: 'u2',
    userName: 'James R.',
    rating: 4,
    title: 'Great coat, runs slightly large',
    comment: 'Beautiful craftsmanship. I would recommend sizing down if you prefer a more fitted look. The navy color is rich and deep.',
    helpful: 18,
    createdAt: '2024-03-15',
  },
  {
    _id: 'r3',
    productId: 'p2',
    userId: 'u3',
    userName: 'Sophie L.',
    rating: 5,
    title: 'Stunning evening dress',
    comment: 'Wore this to a gala and received compliments all night. The silk drapes beautifully and the fit is true to size.',
    helpful: 32,
    createdAt: '2024-03-12',
  },
  {
    _id: 'r4',
    productId: 'p3',
    userId: 'u4',
    userName: 'Marcus T.',
    rating: 5,
    title: 'Best sneakers I own',
    comment: 'The leather quality is outstanding. They look even better in person. Very comfortable for all-day wear.',
    helpful: 45,
    createdAt: '2024-03-08',
  },
  {
    _id: 'r5',
    productId: 'p6',
    userId: 'u5',
    userName: 'Emily K.',
    rating: 5,
    title: 'Perfect gym set',
    comment: 'The fabric is so soft and stretchy. It moves with you during workouts and dries quickly. Already bought a second color.',
    helpful: 28,
    createdAt: '2024-03-18',
  },
];

export const demoUser: User = {
  _id: 'u1',
  name: 'Demo User',
  email: 'user@nova.com',
  avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
  role: 'user',
  addresses: [
    {
      fullName: 'Demo User',
      street: '123 Fashion Ave',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
      phone: '+1 (555) 123-4567',
    },
  ],
  preferences: {
    style: ['minimal', 'classic', 'modern'],
    colors: ['black', 'navy', 'white'],
    sizes: ['M', 'L'],
    categories: ['Men', 'Footwear', 'Accessories'],
  },
  createdAt: '2024-01-01',
};

export const demoAdmin: User = {
  _id: 'a1',
  name: 'Admin User',
  email: 'admin@nova.com',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
  role: 'admin',
  addresses: [],
  preferences: {
    style: [],
    colors: [],
    sizes: [],
    categories: [],
  },
  createdAt: '2024-01-01',
};

export const orders: Order[] = [
  {
    _id: 'o1',
    userId: 'u1',
    items: [
      { product: products[0], quantity: 1, size: 'M', color: 'Black' },
      { product: products[2], quantity: 1, size: '10', color: 'White' },
    ],
    total: 678,
    status: 'delivered',
    shippingAddress: demoUser.addresses[0],
    paymentMethod: 'Credit Card',
    createdAt: '2024-03-01',
    trackingNumber: 'TRK-784932156',
    estimatedDelivery: '2024-03-05',
  },
  {
    _id: 'o2',
    userId: 'u1',
    items: [
      { product: products[5], quantity: 2, size: 'L', color: 'Black' },
    ],
    total: 238,
    status: 'shipped',
    shippingAddress: demoUser.addresses[0],
    paymentMethod: 'PayPal',
    createdAt: '2024-03-15',
    trackingNumber: 'TRK-993847261',
    estimatedDelivery: '2024-03-20',
  },
  {
    _id: 'o3',
    userId: 'u1',
    items: [
      { product: products[8], quantity: 1, size: 'One Size', color: 'Black' },
    ],
    total: 349,
    status: 'processing',
    shippingAddress: demoUser.addresses[0],
    paymentMethod: 'Credit Card',
    createdAt: '2024-03-18',
    trackingNumber: 'TRK-112358132',
    estimatedDelivery: '2024-03-25',
  },
];
